# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - knowledge.md
  - develop.md 
  

footer: 'Подписывайтесь на <a href="https://twitter.com/">Substack</a>'<a href="https://twitter.com/">Boosty</a>'

style: light
#listen_for_clients_preferred_style: true # true or false (default)


plugins:
  - jekyll-seo-tag
  
# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
